#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSExt.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="lansweeperdb")]
	public partial class rPersonalDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertrPersonal(rPersonal instance);
    partial void UpdaterPersonal(rPersonal instance);
    partial void DeleterPersonal(rPersonal instance);
    #endregion
		
		public rPersonalDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["lansweeperdbConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public rPersonalDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public rPersonalDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public rPersonalDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public rPersonalDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<rPersonal> rPersonals
		{
			get
			{
				return this.GetTable<rPersonal>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.rPersonal")]
	public partial class rPersonal : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private System.DateTime _moddate;
		
		private string _Company;
		
		private string _Filial;
		
		private string _Departament;
		
		private string _Upravlenie;
		
		private string _Otdel;
		
		private string _Grupa;
		
		private string _Tabel;
		
		private string _Dolgnost;
		
		private string _FIO;
		
		private string _Familia;
		
		private string _Imya;
		
		private string _Otchestvo;
		
		private System.Nullable<System.DateTime> _Daterp;
		
		private System.Nullable<System.DateTime> _DateUvol;
		
		private string _Status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnmoddateChanging(System.DateTime value);
    partial void OnmoddateChanged();
    partial void OnCompanyChanging(string value);
    partial void OnCompanyChanged();
    partial void OnFilialChanging(string value);
    partial void OnFilialChanged();
    partial void OnDepartamentChanging(string value);
    partial void OnDepartamentChanged();
    partial void OnUpravlenieChanging(string value);
    partial void OnUpravlenieChanged();
    partial void OnOtdelChanging(string value);
    partial void OnOtdelChanged();
    partial void OnGrupaChanging(string value);
    partial void OnGrupaChanged();
    partial void OnTabelChanging(string value);
    partial void OnTabelChanged();
    partial void OnDolgnostChanging(string value);
    partial void OnDolgnostChanged();
    partial void OnFIOChanging(string value);
    partial void OnFIOChanged();
    partial void OnFamiliaChanging(string value);
    partial void OnFamiliaChanged();
    partial void OnImyaChanging(string value);
    partial void OnImyaChanged();
    partial void OnOtchestvoChanging(string value);
    partial void OnOtchestvoChanged();
    partial void OnDaterpChanging(System.Nullable<System.DateTime> value);
    partial void OnDaterpChanged();
    partial void OnDateUvolChanging(System.Nullable<System.DateTime> value);
    partial void OnDateUvolChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    #endregion
		
		public rPersonal()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_moddate", DbType="DateTime NOT NULL")]
		public System.DateTime moddate
		{
			get
			{
				return this._moddate;
			}
			set
			{
				if ((this._moddate != value))
				{
					this.OnmoddateChanging(value);
					this.SendPropertyChanging();
					this._moddate = value;
					this.SendPropertyChanged("moddate");
					this.OnmoddateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company", DbType="NVarChar(255)")]
		public string Company
		{
			get
			{
				return this._Company;
			}
			set
			{
				if ((this._Company != value))
				{
					this.OnCompanyChanging(value);
					this.SendPropertyChanging();
					this._Company = value;
					this.SendPropertyChanged("Company");
					this.OnCompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Filial", DbType="NVarChar(255)")]
		public string Filial
		{
			get
			{
				return this._Filial;
			}
			set
			{
				if ((this._Filial != value))
				{
					this.OnFilialChanging(value);
					this.SendPropertyChanging();
					this._Filial = value;
					this.SendPropertyChanged("Filial");
					this.OnFilialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Departament", DbType="NVarChar(255)")]
		public string Departament
		{
			get
			{
				return this._Departament;
			}
			set
			{
				if ((this._Departament != value))
				{
					this.OnDepartamentChanging(value);
					this.SendPropertyChanging();
					this._Departament = value;
					this.SendPropertyChanged("Departament");
					this.OnDepartamentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Upravlenie", DbType="NVarChar(255)")]
		public string Upravlenie
		{
			get
			{
				return this._Upravlenie;
			}
			set
			{
				if ((this._Upravlenie != value))
				{
					this.OnUpravlenieChanging(value);
					this.SendPropertyChanging();
					this._Upravlenie = value;
					this.SendPropertyChanged("Upravlenie");
					this.OnUpravlenieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Otdel", DbType="NVarChar(255)")]
		public string Otdel
		{
			get
			{
				return this._Otdel;
			}
			set
			{
				if ((this._Otdel != value))
				{
					this.OnOtdelChanging(value);
					this.SendPropertyChanging();
					this._Otdel = value;
					this.SendPropertyChanged("Otdel");
					this.OnOtdelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grupa", DbType="NVarChar(255)")]
		public string Grupa
		{
			get
			{
				return this._Grupa;
			}
			set
			{
				if ((this._Grupa != value))
				{
					this.OnGrupaChanging(value);
					this.SendPropertyChanging();
					this._Grupa = value;
					this.SendPropertyChanged("Grupa");
					this.OnGrupaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tabel", DbType="NVarChar(255)")]
		public string Tabel
		{
			get
			{
				return this._Tabel;
			}
			set
			{
				if ((this._Tabel != value))
				{
					this.OnTabelChanging(value);
					this.SendPropertyChanging();
					this._Tabel = value;
					this.SendPropertyChanged("Tabel");
					this.OnTabelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dolgnost", DbType="NVarChar(255)")]
		public string Dolgnost
		{
			get
			{
				return this._Dolgnost;
			}
			set
			{
				if ((this._Dolgnost != value))
				{
					this.OnDolgnostChanging(value);
					this.SendPropertyChanging();
					this._Dolgnost = value;
					this.SendPropertyChanged("Dolgnost");
					this.OnDolgnostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIO", DbType="NVarChar(255)")]
		public string FIO
		{
			get
			{
				return this._FIO;
			}
			set
			{
				if ((this._FIO != value))
				{
					this.OnFIOChanging(value);
					this.SendPropertyChanging();
					this._FIO = value;
					this.SendPropertyChanged("FIO");
					this.OnFIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Familia", DbType="NVarChar(255)")]
		public string Familia
		{
			get
			{
				return this._Familia;
			}
			set
			{
				if ((this._Familia != value))
				{
					this.OnFamiliaChanging(value);
					this.SendPropertyChanging();
					this._Familia = value;
					this.SendPropertyChanged("Familia");
					this.OnFamiliaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Imya", DbType="NVarChar(255)")]
		public string Imya
		{
			get
			{
				return this._Imya;
			}
			set
			{
				if ((this._Imya != value))
				{
					this.OnImyaChanging(value);
					this.SendPropertyChanging();
					this._Imya = value;
					this.SendPropertyChanged("Imya");
					this.OnImyaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Otchestvo", DbType="NVarChar(255)")]
		public string Otchestvo
		{
			get
			{
				return this._Otchestvo;
			}
			set
			{
				if ((this._Otchestvo != value))
				{
					this.OnOtchestvoChanging(value);
					this.SendPropertyChanging();
					this._Otchestvo = value;
					this.SendPropertyChanged("Otchestvo");
					this.OnOtchestvoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Daterp", DbType="DateTime")]
		public System.Nullable<System.DateTime> Daterp
		{
			get
			{
				return this._Daterp;
			}
			set
			{
				if ((this._Daterp != value))
				{
					this.OnDaterpChanging(value);
					this.SendPropertyChanging();
					this._Daterp = value;
					this.SendPropertyChanged("Daterp");
					this.OnDaterpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateUvol", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateUvol
		{
			get
			{
				return this._DateUvol;
			}
			set
			{
				if ((this._DateUvol != value))
				{
					this.OnDateUvolChanging(value);
					this.SendPropertyChanging();
					this._DateUvol = value;
					this.SendPropertyChanged("DateUvol");
					this.OnDateUvolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(10)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
